name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository ğŸ› ï¸
              uses: actions/checkout@v4

            - name: Setup ğŸ› ï¸
              uses: ./.github/actions/setup
              with:
                  node-version: '20'

            - name: Get remot diccionari etag
              id: diccionari-etag
              shell: bash
              run: |
                  echo "ETAG=$(curl --head --location https://github.com/Softcatala/catalan-dict-tools/raw/refs/heads/master/resultats/lt/diccionari.txt | grep -i etag)" >> $GITHUB_OUTPUT

            - name: Cache diccionary dependencies
              id: diccionari-cache
              uses: actions/cache@v3
              with:
                  path: diccionari/.etag
                  key: diccionari-${{steps.diccionari-etag.outputs.ETAG}}

            - name: Download diccionary ğŸ“¥
              if: steps.diccionari-cache.outputs.cache-hit != 'true'
              shell: bash
              run: |
                  curl -o diccionari/index.txt https://raw.githubusercontent.com/Softcatala/catalan-dict-tools/refs/heads/master/resultats/lt/diccionari.txt

            - name: Prevent heroku shallow error ğŸš«
              run: |
                  git fetch --unshallow
              shell: bash

            - name: Build project ğŸ—ï¸
              run: yarn build:server

            - name: Copy diccionari to dist ğŸ—ƒï¸
              run: |
                  mkdir -p dist-server/diccionari
                  cp -r diccionari/* dist-server/diccionari/
              shell: bash

            - name: Setup Heroku CLI ğŸŒ
              run: |
                  cd dist-server
                  npm init -y
                  npm pkg set scripts.start="node index.js"
                  cd -
              shell: bash

            - name: Add remote origin
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
              run: |
                git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
              shell: bash

            - name: Commit changes for Heroku
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git add -f dist-server
                  git commit -nm "Prepare deployment to Heroku"

            - name: Deploy to Heroku ğŸš€
              run: |
                  git subtree split --prefix dist-server -b deploy-branch
                  git push heroku deploy-branch:main --force
                  git branch -D deploy-branch
