name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository ðŸ› ï¸
              uses: actions/checkout@v4

            - name: Setup ðŸ› ï¸
              uses: ./.github/actions/setup
              with:
                  node-version: '20'

            - name: Get remot diccionari etag
              id: diccionari-etag
              shell: bash
              run: |
                  echo "ETAG=$(curl --head --location https://github.com/Softcatala/catalan-dict-tools/raw/refs/heads/master/resultats/lt/diccionari.txt | grep -i etag)" >> $GITHUB_OUTPUT

            - name: Cache diccionary dependencies
              id: diccionari-cache
              uses: actions/cache@v3
              with:
                  path: diccionari/.etag
                  key: diccionari-${{steps.diccionari-etag.outputs.ETAG}}

            - name: Download diccionary ðŸ“¥
              if: steps.diccionari-cache.outputs.cache-hit != 'true'
              shell: bash
              run: |
                  curl -o diccionari/index.txt https://raw.githubusercontent.com/Softcatala/catalan-dict-tools/refs/heads/master/resultats/lt/diccionari.txt

            - name: Prevent heroku shallow error ðŸš«
              run: git fetch --unshallow
              shell: bash

            - name: Build project ðŸ—ï¸
              run: yarn build:server

            - name: Copy diccionari to dist ðŸ—ƒï¸
              run: |
                  mkdir -p dist-server/diccionari
                  cp -r diccionari/* dist-server/diccionari/
              shell: bash

            - name: Deploy to Heroku ðŸš€
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
              run: |
                  echo "machine api.heroku.com" > ~/.netrc
                  echo "  login $HEROKU_API_KEY" >> ~/.netrc
                  echo "  password $HEROKU_API_KEY" >> ~/.netrc
                  echo "machine git.heroku.com" >> ~/.netrc
                  echo "  login $HEROKU_API_KEY" >> ~/.netrc
                  echo "  password $HEROKU_API_KEY" >> ~/.netrc
                  yarn global add heroku
                  heroku git:remote -a $HEROKU_APP_NAME
                  git push heroku $(git subtree split --prefix dist-server main) --force-with-lease
