name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository ðŸ› ï¸
              uses: actions/checkout@v4

            - name: Setup ðŸ› ï¸
              uses: ./.github/actions/setup
              with:
                  node-version: '20'

            - name: Build project ðŸ—ï¸
              run: yarn build:server

            - name: Prevent heroku shallow error ðŸš«
              run: |
                  [[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow
              shell: bash

            - name: Deploy to Heroku ðŸš€
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
              run: |
                  echo "machine api.heroku.com" > ~/.netrc
                  echo "  login $HEROKU_API_KEY" >> ~/.netrc
                  echo "  password $HEROKU_API_KEY" >> ~/.netrc
                  echo "machine git.heroku.com" >> ~/.netrc
                  echo "  login $HEROKU_API_KEY" >> ~/.netrc
                  echo "  password $HEROKU_API_KEY" >> ~/.netrc
                  yarn global add heroku
                  heroku git:remote -a $HEROKU_APP_NAME
                  git push heroku $(git subtree split --prefix dist-server main) --force-with-lease
